version: '2.0'
services:

  bootnode:
    build: bubble_geth
    restart: on-failure
    container_name: bubble_geth
    ports:
      - "31333:31333"
      - "31333:31333/udp"
      - "8538:8538"
    networks:
      app_net:
        ipv4_address: 192.168.10.20

  parity0:
    build: bubble_parity
    restart: on-failure
    container_name: bubble_parity
    command:
      --chain /bubble_parity/parity.json
      --port 31337
      --jsonrpc-port 8539
      --bootnodes enode://407759ac27f5a65eb03bc58fc7174010c9f63bbabb3bd66aca3a0268ceee96c956e3cd0506fbb90a9ac61004e8f60c1e22cc6d35bf4d92a4deab01d6a3755d61@192.168.10.20:31333
    ports:
      - 31337:31337
      - 8539:8539
    networks:
      app_net:
        ipv4_address: 192.168.10.10

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.10.1/24
        gateway: 192.168.10.1
